from __future__ import annotations

import argparse
import json
from pathlib import Path

from overlay_localization_common import parse_text_bundle


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Import a plain-text translation file back into a JSON bundle."
    )
    parser.add_argument("--bundle", required=True, help="Source JSON bundle path.")
    parser.add_argument(
        "--text-input",
        required=True,
        help="Plain-text translation file generated by export_bundle.py --text-output.",
    )
    parser.add_argument(
        "--output-bundle",
        default=None,
        help="Output JSON bundle path. Defaults to overwriting --bundle.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    bundle_path = Path(args.bundle).resolve()
    text_input_path = Path(args.text_input).resolve()
    output_bundle_path = (
        Path(args.output_bundle).resolve() if args.output_bundle else bundle_path
    )

    bundle = json.loads(bundle_path.read_text(encoding="utf-8-sig"))
    translations = parse_text_bundle(text_input_path.read_text(encoding="utf-8-sig"))

    updated_entries = 0
    matched_entries = 0
    for file_info in bundle.get("files", []):
        for entry in file_info.get("entries", []):
            entry_id = str(entry["id"])
            if entry_id not in translations:
                continue
            matched_entries += 1
            new_translation = translations[entry_id]
            if entry.get("translation", "") != new_translation:
                entry["translation"] = new_translation
                updated_entries += 1

    output_bundle_path.parent.mkdir(parents=True, exist_ok=True)
    output_bundle_path.write_text(
        json.dumps(bundle, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"Text bundle read: {text_input_path}")
    print(f"JSON bundle written: {output_bundle_path}")
    print(f"Entries matched: {matched_entries}")
    print(f"Entries updated: {updated_entries}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
